services:
  bot:
    container_name: "Estella"
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - path: ./ext
          action: sync
          target: /app/ext
    env_file:
      - .env
    environment:
      # Required
      TOKEN:
      DEFAULT_PREFIX:

      # Optional
      LOG_FUNNEL_WEBHOOK:
    volumes:
      - /data/estella:/app/db/
